Update tbcQuestFixes.lua
Questie/Questie pull request #2662
Opened 2021-04-28 19:27 UTC by GillsITWorld

Add Extra Objectives for Quest 11885 (Fix 2 of 2)
Tested on Beta

2021-04-28 19:58 UTC, BreakBB commented
Hey @GillsITWorld thanks for taking your time and digging into the Questie corrections!

Let me explain two things, which will hopefully help you with this and future PRs for quest corrections :)

1) The `extraObjective` field can also take database references, so you don't have to copy over spawns of existing NPCs/objects. But you couldn't know this since the explanation of the `extraObjective` field is not complete (yet), sorry 🙈 You would add a database reference like this:

```lua
        [8490] = {
            [questKeys.extraObjectives] = {{nil, ICON_TYPE_EVENT, "Place the Infused Crystal and protect it from the Scourge for 1 minute", 0, {{"object", 181164}}}}
        },
```

After the `0` for an optional objective index, you open another table which contains pairs of the database type you want to reference (npc, object, item) and the ID of the reference. The example above references the object 181164.

2) We actually don't want to show the "spawns" of NPCs which spawn you have to trigger in some way. Instead mark the location where you have to summon something/someone. This could be done either with an `ICON_TYPE_OBJECT` if you have to interact with some game object or `ICON_TYPE_EVENT` if you have to use a quest item.

Also in most cases you don't need the indivdual spawns at the beginning of the `extraObjectives` field, but can reference an object where something has to happen. 

For the quest you are trying to fix [Adversarial Blood](https://www.wowhead.com/quest=11885/adversarial-blood) you want to search for the "Skull Pile" object with which you can summon the NPCs you have to kill.

Hit me up on Discord or simply ask here if you have more questions. I am always happy to get help fixing all the quest bugs 😁

2021-04-28 20:24 UTC, GillsITWorld commented
Ok, I understand this, so how do we label/icon who you farm to get the Time-Lost Scrolls from to be able to use the Skull Piles?

2021-04-28 20:39 UTC, GillsITWorld commented
[https://i.imgur.com/YxRKN17.png](url)

https://imgur.com/YxRKN17

2021-04-28 20:54 UTC, BreakBB commented
Items you need to complete the objectives, but which are not the objectives themself can be added with the `requiredSourceItem` field. As long as the item is linked to NPCs those are shown on the map just fine.

Also above you have a "Red" in your color code which shouldn't be there. And I am not really sure what to say about the formatting of the text you did. It is a great idea, but there should be a standard way to do this 🤔 For now it would be better to remove the formatting as it should not be directly included in the database imo.

2021-04-28 20:55 UTC, GillsITWorld commented
So remove the color codes, leave basic text?

2021-04-28 21:07 UTC, BreakBB commented
For now that would be perfect yes.

Optionally create an issue with your suggestion towards the formatting, since that makes it even easier to understand what to do/use when and where and how :)

2021-05-02 08:55 UTC, BreakBB requested changes

2021-05-02 08:55 UTC, BreakBB commented on Database/Corrections/TBC/tbcQuestFixes.lua
> +            [questKeys.extraObjectives] = {{{[zoneIDs.TEROKKAR_FOREST]={{61,78.8},{61.4,75.4},{61.4,75.6},{61.4,78},{61.6,78},{61.8,75.6},{62,75},{62.2,74.4},{65.8,79.4},{66,79.6},{6.8,80.2},{68.4,85
Remove the spawnlist, add a dbReference and remove the text formatting (for now) :)

2021-05-02 09:47 UTC, BreakBB commented
Closing this in favor of #2690

2021-05-02 09:47 UTC, closed without merging