Refactor quest event system
Questie/Questie pull request #3111
Opened 2021-08-05 19:49 UTC by BreakBB

2021-08-05 20:00 UTC, Laumesis commented
My first catch of `QUEST_REMOVED` event firing before `QUEST_TURNED_IN` event.  Note that there also is **no** `UNIT_QUEST_LOG_CHANGED` or `QUEST_LOG_UPDATE` after `QUEST_TURNED_IN`.
Player turned it midsummer non-daily quest `Playing with Fire` (11882).

![image](https://user-images.githubusercontent.com/75958501/128413300-7932dbf9-be69-4905-bec5-aad8af581ee3.png)

2021-08-05 20:19 UTC, Laumesis commented
Alliance player clicked horde bonfire to start `Desecrate this Fire!` (11786) non-daily midsummer quest, but didn't turn it in even completion dialog appeared. Then player clicked the bonfire to start the quest again and this time turned it in.

This is instant quest that doesn't visit player quest log at all. It is most likely yearly repeatable.

Note: There is not `QUEST_REMOVED` event at all. But there is `QUEST_LOG_UPDATE` event after `QUEST_TURNED_IN` event - most likely because player received such item that it triggered possible quest log ui update.

![image](https://user-images.githubusercontent.com/75958501/128415455-054a482e-0462-433a-a35b-dcf103b9059f.png)

2021-08-05 20:28 UTC, Laumesis commented
Similar case as previous comment ( https://github.com/Questie/Questie/pull/3111#issuecomment-893769548 ).

Alliance player talked to alliance quest giver ncp to complete quest `Honor the Flame` (11813). No abondons between or such. Just direct talk, select quest and turn in.

This is instant quest, so it didn't visit player quest log. So no `QUEST_REMOVED` or `UNIT_QUEST_LOG_CHANGED` did not fire at all. There is `QUEST_LOG_UPDATE` event after turn in, but it is likely because of received reward item.

![image](https://user-images.githubusercontent.com/75958501/128416725-e493f1cc-81ee-4405-9f8a-28f20ed9fefb.png)

2021-08-05 20:35 UTC, Laumesis commented
Repeatable instant quest test-case quest in Elwyn Forest.  Quest `Give Gerard a Drink` (16). Big thanks to @Muehe for telling this quest.

Player talks to quest giver npc, and does the turn in without any abandon testings.

The quest won't visit quest log as it is instant item turn in. Note there is no quest log related events **at all**. No `QUEST_ACCEPTED`, no `QUEST_REMOVED`, no `UNIT_QUEST_LOG_CHANGED`, no `QUEST_LOG_UPDATE`.

![image](https://user-images.githubusercontent.com/75958501/128417464-5c864659-d97a-47bb-8740-a6ec7598f75a.png)

2021-08-05 20:45 UTC, Laumesis commented
Regular quest take case to show `QUEST_ACCEPTED` event. Nothing fancy to see.

![image](https://user-images.githubusercontent.com/75958501/128418684-ddd74bb6-e41a-4d72-ba55-0dc492862588.png)

2021-08-05 21:01 UTC, Laumesis commented
Player took midsummer daily quests `More Torch Catching` (11924) and `More Torch Tossing` (11921). Then player did quest objectives of both quests and returned to quest giver npc. Player turned in both quests fast without any tricks - just clicking regular dialog frames with a mouse. Player gained a level when turned in latter of the quests.

This is again rare randomly occuring case where `QUEST_REMOVED` event fired before `QUEST_TURNED_IN` event. This happend when turning in latter the quests. I have noticed that player gaining a level from quest turn in increase chance of `QR` firing before `QTI`.

There are two `QUEST_LOG_UPDATE` events after `QUEST_REMOVED`. First one is likely because quest was removed from player quest log and 2nd because player received such item to set to trigger it. Or other way around 🤷 


![image](https://user-images.githubusercontent.com/75958501/128420333-e3f08798-2ce1-4053-9715-d0dfc14cd29d.png)

2021-08-05 23:50 UTC, Laumesis commented
Proposed new logic to fix desync. Originating this PR.
Has to be converted to Questie code and logic added for tracker / journey / other stuff. Updating tracker and map could maybe rely on `UNIT_QUEST_LOG_CHANGED` or `QUEST_LOG_UPDATE` with some throttling?

Original at https://pastebin.com/5s1e8MHT (expires in 1 year). Changes here compared to the original.
- Better commenting
- Few print messages modified without changing meanig
- Added missing `questsLastEvent[questId] = 0` into for loop in `PLAYER_LOGIN` handling

```lua
--- Used for detecting abandoning a quest.
--- Needed because QUEST_TURN_IN can fire before or after QUEST_REMOVED (and other questlog events).
--- [questid] = nil, 0, 1, 2, timerHandle
--- nil -> Not seen quest during session.
--- 0 -> Last event was QUEST_ACCEPTED
--- 1 -> Last event was QUEST_TURNED_IN
--- 2 -> Last event was QUEST_REMOVED -- this could aswell be nil, but more understandable this way
--- timerHandle -> Last event was QUEST_REMOVED and
---                waiting possible QUEST_TURNED_IN to decide if quest was Abandoned
---@type table<nil | number, nil | number | table>
local questsLastEvent = {}
local frame = CreateFrame("Frame") -- TODO: Rename

local function questsLastEventHandler(_, event, ...)
    if event == "QUEST_ACCEPTED" then -- args: questLogIndex, questId
        local questId, _ = select(2, ...)
        local lastEvent = questsLastEvent[questId]
        print("QUEST_ACCEPTED", questId, tostring(lastEvent))

        -- Check if timer is running
        --    -> We have picked up the quest quickly again after abandon
        --    -> Cancel the timer and do quest Abandoned stuff.
        if lastEvent and type(lastEvent) ~= "number" then
            lastEvent:Cancel()
            print("QUEST_ACCEPTED timer:Cancel()", questId)
            -- Executing same stuff as the timer would do (but not error check).
            print("QUEST_ACCEPTED Quest Abandoned", questId)
            -- TODO call quest abandon stuff elsewhere in Questie
        end

        questsLastEvent[questId] = 0
        -- TODO call quest accept stuff elsewhere in Questie

    elseif event == "QUEST_TURNED_IN" then -- args: questId, xpReward, moneyReward
        local questId, _ = select(1, ...)
        local lastEvent = questsLastEvent[questId]
        print("QUEST_TURNED_IN", questId, tostring(lastEvent))

        -- Check if timer is running -> It wasn't abandon but turning in -> Just cancel the timer
        if lastEvent and type(lastEvent) ~= "number" then
            lastEvent:Cancel()
            print("QUEST_TURNED_IN timer:Cancel()", questId)
        end

        questsLastEvent[questId] = 1
        -- TODO call quest turn in stuff elsewhere in Questie

    elseif event == "QUEST_REMOVED" then -- args: questId
        -- Can be quest abandon or quest turn in
        local questId, _ = select(1, ...)
        local lastEvent = questsLastEvent[questId]
        print("QUEST_REMOVED", questId, tostring(lastEvent))

        -- Possible TODO: Add logic to abandon non-completed quests directly without timer (not mandatory for functioning correctly)

        -- We can abandon only quests from our quest log, so those must be in ACCEPTED state
        if lastEvent and type(lastEvent) == "number" and lastEvent == 0 then
            print("QUEST_REMOVED starting timer")
            questsLastEvent[questId] = C_Timer.NewTicker(2, -- Using Ticker to be able to Cancel() -- 2 seconds
            function ()
                local lastEvent = questsLastEvent[questId]
                -- Check if we don't have timer reference as lastEvent.
                -- Timer should have been canceled in that case and this code shouldn't get executed.
                if (not lastEvent) or type(lastEvent) == "number" then
                    print("ERROR: Quest abandoning timer should not have been executed. Report this to developers. QuestId = "..questId..", lastEvent = "..tostring(lastEvent))
                    -- Do nothing as we are kind of screwed anyway. TODO: better handling of this not-possible-error-case?
                    return
                end
                print("Timer: Quest Abandoned", questId)
                questsLastEvent[questId] = 2
                -- TODO call quest avandon stuff elsewhere in Questie
            end,
            1) -- Timer gets executed only one time
        else
            -- If we got 'QUEST_REMOVED' while in other state, it can't be abandon.
            -- lastEvent == nil -> not ACCEPTED yet, so not in quest log -> can't be abandoned
            -- lastEvent == 1 or 2 or timerHandle -> not ACCEPTED yet after previous TURN_IN or ABANDON, so not in quest log -> can't be abandoned.
            questsLastEvent[questId] = 2
        end
    elseif event == "PLAYER_LOGIN" then
        print("PLAYER_LOGIN")
        -- Initialize questsLastEvents table with current quest log quests
        -- TODO: PLAYER_LOGIN is not reliable event to load quest log state:
        --     game client cache can be wrong and serve gives new data later?
        --     if we had timed quest at logout, it can be removed and we don't notice it here.
        --     first QUEST_LOG_UPDATE might be better moment to run this. needs testing! it might need to forced to get triggered.
        local numEntries, _ = GetNumQuestLogEntries()
        for i=1, numEntries do
            local _, _, _, isHeader, _, _, _, questId, _ = GetQuestLogTitle(i)
            if not isHeader then
                print("Setting quest accepted at login", questId)
                questsLastEvent[questId] = 0
                -- TODO call quest accept stuff elsewhere in Questie (except this is done at PLAYER_LOGIN way before Questie is ready for calls)
            end
        end
    end
end

frame:RegisterEvent("PLAYER_LOGIN")
frame:RegisterEvent("QUEST_ACCEPTED")
frame:RegisterEvent("QUEST_TURNED_IN")
frame:RegisterEvent("QUEST_REMOVED")
frame:SetScript("OnEvent", questsLastEventHandler)
```

2021-08-06 02:11 UTC, Laumesis commented
Some of known event orders when a quest is turned in:
- Accepted earlier -> `QUEST_TURNED_IN` -> `UNIT_QUEST_LOG_CHANGED` -> `QUEST_REMOVED` -> `QUEST_LOG_UPDATE` (the normal case)
- Accepted earlier -> `UNIT_QUEST_LOG_CHANGED` -> `QUEST_REMOVED` -> `QUEST_LOG_UPDATE` -> `QUEST_TURNED_IN` (a desync case)
- Accepted earlier -> `UNIT_QUEST_LOG_CHANGED` -> `QUEST_REMOVED` -> `QUEST_LOG_UPDATE` -> `QUEST_TURNED_IN` -> `QUEST_LOG_UPDATE` (a desync case)
- `QUEST_TURNED_IN` -> `QUEST_LOG_UPDATE` (a instant turn in quest which rewarded or consumed some item to/from player's inventory. and the item was marked to trigger `QLU`)
- `QUEST_TURNED_IN` (same as previous, without triggering `QLU`)

So we can see there are atleast two type of quests:
- Those that go via player quest log (normal ones)
- Those that won't go (instant quests)

Other notes seen and figured:
- A quest must go via player quest log for player to be able to abandon it
Abandon function in WoW API requires first selecting a quest from quest lof via other WoW API call.
- `QUEST_LOG_UPDATE` seems to fire when there is possible change for QuestLogFrame related things maybe tracker too?
- Order of  "quest log related events" and `QUEST_TURNED_IN` event can be either way, but `QUEST_TURNED_IN` fires *usually* first. Game server seems to process first mentioned group of events and latter mentioned event somewhat separately. Time difference between those is usually at most in tens of milliseconds when there is *no server side lag*.
- A failed quest can be `QUEST_ACCEPTED` (accepted) again without first `QUEST_REMOVED` (abandoning) it from quest log.
- A quest can get removed from player quest log while player is offline (or during login process, I am not sure which one).
This can happen at least when a quest with time requirement for completing it times out while player is offline.
The state read at `PLAYER_LOGIN` event won't necessary reflect this remove. Maybe game client has local cache which is not yet updated to match server side state.
Should be tested if player quest log content is valid at `ENTERING_WORLD` event. And if not then I would *assume* it to be valid at (both or just one of these, needs testing)  (I assume because of guild info text behavior):
  - first `QUEST_LOG_UPDATE` event
  - if  state at `ENTERING_WORLD` (login or reload) event was invalid, then first `UNIT_QUEST_LOG_CHANGED` might fire soon at login without player actions and fix state to valid.
- If valid player quest log can't be read at previous point cases, there might be need for comparing quests in quest log at each `QUEST_LOG_UPDATE` event. This is worst case and not wanted for this logic.
Tracker and map icon updates may still require this always, not related to reading valid player quest log at player login/reload.
- "Chat message" events related to quest progress are not deterministically ordered/timed vs. corresponding quest events.
- `QUEST_COMPLETE` and `QUEST_FINISHED` ui frame show/hide events could be used to reduce times when we need a timer, but benefit from it is questionable as timer should be needed so parsely anyway.
  - quest can be abandoned while we are in between those two events, so it can't be used to exclude abandon fully
  - if used to reduce cases, we must take into account possible loading screens hiding player ui -> must test if those fire `QUEST_FINISHED`

Assumptions for logic:
- `QUEST_ACCEPTED` fires every time a quest is accepted and added to player quest log
 - Needs testing will it fire when a failed quest is started again without abandoning it first.
   Doesn't really affect function of quest turn in / abandon, but would affect tracket and map icons and journey and such.
- when doing repeatable quest `QUEST_ACCEPTED` won't fire before `QUEST_REMOVED` and `QUEST_TURNED_IN` events, which are related to turning the quest previous time
- `QUEST_TURNED_IN` fires every time a quest is turned in
- `QUEST_REMOVED` fires every time a quest is abandoned
- A quest can be abandoned only if it is first `QUEST_ACCEPTED` into quest log.

p.s. tiredness shut of my brains near start of this comment, but I tried to gather all stuff mentioned in discord

2021-08-06 13:49 UTC, Laumesis commented
Nothing special. Player turning in midsummer dailies. Just a /etrace log to see normal event flow. Some events filtered out, so use absolute times to compare delays.

![image](https://user-images.githubusercontent.com/75958501/128520241-0874e80d-ed00-4084-9e54-3b93b1a89a78.png)

2021-08-06 14:22 UTC, Laumesis commented
Nothing special. All events related to quest turn arrived at same frame. Order seems typical, except I don't know typical position of `PLAYER_LEVEL_CHANGED`, so no idea if order for that one is typical or not.

Player turned in two midsummer dailies and gained a level when turning in 2nd one. That 2nd turn in is in the screenshot blow.

![image](https://user-images.githubusercontent.com/75958501/128524673-031fe7af-01fa-4e69-a937-f0d869578536.png)

2021-08-07 16:09 UTC, Laumesis commented
Player taking both midsummer torch dailie. While doing one, the timed one runs out of time and fails, so picking it up again without abandon first. Turning in both after they both are completed.

`QuestLog:` has player quest log queried from api at that point. `f` at end means quest is in failed state and `c` in completed state.

```
[18:57:02] PLAYER_LOGIN QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[18:57:02] Setting quest accepted at login 6821
[18:57:02] Setting quest accepted at login 4764
[18:57:02] Setting quest accepted at login 9664
[18:57:02] Setting quest accepted at login 9211
[18:57:02] Setting quest accepted at login 9213
[18:57:02] Setting quest accepted at login 9141
[18:57:02] Setting quest accepted at login 10254
[18:57:02] Setting quest accepted at login 11924
[18:57:02] Setting quest accepted at login 11921
[18:57:02] PLAYER_ENTERING_WORLD isInitialLogin = true isReloadingUi = false QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[18:57:02] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[18:57:02] QUEST_WATCH_LIST_CHANGED nil nil
[18:57:03] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[18:57:04] [Questie] The 'Midsummer' world event is active!
[18:57:04] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[18:57:07] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921c
[18:57:07] QUEST_REMOVED 11924 0 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921c
[18:57:07] QUEST_REMOVED starting timer
[18:57:08] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921c
[18:57:10] Timer: Quest Abandoned 11924
[18:57:13] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921
[18:57:13] QUEST_REMOVED 11921 0 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254
[18:57:13] QUEST_REMOVED starting timer
[18:57:13] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254
[18:57:15] Timer: Quest Abandoned 11921
[18:57:26] You receive item: [Practice Torches].
[18:57:27] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254
[18:57:27] Quest accepted: More Torch Tossing
[18:57:27] QUEST_ACCEPTED 11921 2 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921
[18:57:27] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921
[18:57:28] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921
[18:57:29] You receive item: [Unlit Torches].
[18:57:29] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11921
[18:57:29] Quest accepted: More Torch Catching
[18:57:29] QUEST_ACCEPTED 11924 2 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921
[18:57:29] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921
[18:57:30] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921
[18:57:31] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921
[18:58:56] More Torch Tossing failed.
[18:58:56] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921f
[18:58:56] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921f
[18:58:57] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921f
[18:59:04] QUEST_WATCH_LIST_CHANGED 11924 true
[18:59:04] QUEST_WATCH_LIST_CHANGED 11924 false
[18:59:04] QUEST_WATCH_UPDATE 11924 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924, 11921f
[18:59:04] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921f
[18:59:04] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921f
[18:59:05] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921f
[18:59:19] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921
[18:59:19] Quest accepted: More Torch Tossing
[18:59:19] QUEST_ACCEPTED 11921 0 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921
[18:59:19] You receive item: [Practice Torches].
[18:59:19] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921
[18:59:20] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921
[19:00:47] QUEST_WATCH_LIST_CHANGED 11921 true
[19:00:47] QUEST_WATCH_LIST_CHANGED 11921 false
[19:00:47] QUEST_WATCH_UPDATE 11921 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921
[19:00:48] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[19:00:48] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[19:00:49] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[19:01:03] You gain 9550 experience.
[19:01:03] You receive item: [Burning Blossom]x5.
[19:01:03] More Torch Tossing completed.
[19:01:03] Experience gained: 9550.
[19:01:03] Received 90 Silver.
[19:01:03] QUEST_TURNED_IN 11921 0 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921c
[19:01:03] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c, 11921
[19:01:03] QUEST_REMOVED 11921 1 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c
[19:01:03] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c
[19:01:05] You gain 9550 experience.
[19:01:05] You receive item: [Burning Blossom]x5.
[19:01:05] More Torch Catching completed.
[19:01:05] Experience gained: 9550.
[19:01:05] Received 90 Silver.
[19:01:05] QUEST_TURNED_IN 11924 0 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924c
[19:01:05] UNIT_QUEST_LOG_CHANGED (player) QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254, 11924
[19:01:05] QUEST_REMOVED 11924 1 QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254
[19:01:05] QUEST_LOG_UPDATE QuestLog: 6821, 4764, 9664, 9211, 9213, 9141, 10254
```

2021-08-07 16:39 UTC, Laumesis commented
@BreakBB This won't work as the cache can have quests, but it is invalid. Also even with invalid cache the log can have valid data at `PLAYER_LOGIN`, it just is not quaranteed.
```lua
    -- Without cached information the first QLU does not have any quest log entries. After 5 tries we stop trying
    if numEntries == 0 and initTries < 5 then
```

2021-08-07 16:59 UTC, Laumesis commented
Player login with delete game cache. Some quests are tracked.
```
[19:41:21] PLAYER_LOGIN QuestLog: empty
[19:41:21] PLAYER_ENTERING_WORLD isInitialLogin = true isReloadingUi = false QuestLog: empty
[19:41:21] QUEST_LOG_UPDATE QuestLog: empty
[19:41:21] QUEST_WATCH_LIST_CHANGED nil nil
[19:41:21] QUEST_LOG_UPDATE QuestLog: 8712, 8657, 8626, 8659, 9521c, 10482, 10141, 10055, 9033, 9248, 8332, 9419, 8620, 5253, 11953
[19:41:23] QUEST_LOG_UPDATE QuestLog: 8712, 8657, 8626, 8659, 9521c, 10482, 10141, 10055, 9033, 9248, 8332, 9419, 8620, 5253, 11953
<removed tens of repeating events>
[19:41:26] QUEST_LOG_UPDATE QuestLog: 8712, 8657, 8626, 8659, 9521c, 10482, 10141, 10055, 9033, 9248, 8332, 9419, 8620, 5253, 11953
```

Player login with deleted game cache. No tracked quests. And this time QuestLog content debug-logged also at `QUEST_WATCH_LIST_CHANGE`
```
[19:57:26] PLAYER_LOGIN QuestLog: empty
[19:57:26] PLAYER_ENTERING_WORLD isInitialLogin = true isReloadingUi = false QuestLog: empty
[19:57:26] QUEST_LOG_UPDATE QuestLog: empty
[19:57:26] QUEST_WATCH_LIST_CHANGED nil nil QuestLog: empty
[19:57:26] QUEST_LOG_UPDATE QuestLog: 8712, 8657, 8626, 8659, 9521c, 10482, 10141, 10055, 9033, 9248, 8332, 9419, 8620, 5253, 11953
[19:57:27] QUEST_LOG_UPDATE QuestLog: 8712, 8657, 8626, 8659, 9521c, 10482, 10141, 10055, 9033, 9248, 8332, 9419, 8620, 5253, 11953
<removed tens of repeating events>
[19:57:30] QUEST_LOG_UPDATE QuestLog: 8712, 8657, 8626, 8659, 9521c, 10482, 10141, 10055, 9033, 9248, 8332, 9419, 8620, 5253, 11953
```

2021-08-07 17:10 UTC, Laumesis commented
Some more logins with deleted game cache.

No quests tracked:
```
[20:05:31] PLAYER_LOGIN QuestLog: empty
[20:05:31] PLAYER_ENTERING_WORLD isInitialLogin = true isReloadingUi = false QuestLog: empty
[20:05:31] QUEST_LOG_UPDATE QuestLog: empty
[20:05:31] QUEST_WATCH_LIST_CHANGED nil nil QuestLog: empty
[20:05:31] QUEST_LOG_UPDATE QuestLog: empty
[20:05:31] QUEST_LOG_UPDATE QuestLog: 11921f
[20:05:32] [Questie] The 'Midsummer' world event is active!
[20:05:32] QUEST_LOG_UPDATE QuestLog: 11921f
<removed 12 repeats of previous debug message>
[20:05:33] QUEST_LOG_UPDATE QuestLog: 11921f
```

And with empty quest log:
```
[20:09:02] PLAYER_LOGIN QuestLog: empty
[20:09:02] PLAYER_ENTERING_WORLD isInitialLogin = true isReloadingUi = false QuestLog: empty
[20:09:02] QUEST_LOG_UPDATE QuestLog: empty
[20:09:02] QUEST_WATCH_LIST_CHANGED nil nil QuestLog: empty
[20:09:02] QUEST_LOG_UPDATE QuestLog: empty
[20:09:03] [Questie] The 'Midsummer' world event is active!
[20:09:04] QUEST_LOG_UPDATE QuestLog: empty
<removed 15 repeats of previous debug message>
[20:09:06] QUEST_LOG_UPDATE QuestLog: empty
```

2021-08-08 21:27 UTC, Laumesis commented
F_cked up local game cache at login having quests, but not all of those. 2nd `QLU`s at login (which was also last of login loading progress) had correct ones. No Questie enabled.
I didn't even do anything to try trigger this. It just happend by itself 🤷‍♂️

![image](https://user-images.githubusercontent.com/75958501/128646200-12d63c42-47d2-4cff-945c-d8e11a35db8e.png)

2021-08-10 22:36 UTC, Laumesis commented
Can we really do these? Will we miss next required update after for example 20 sconds because this skip?

https://github.com/Questie/Questie/blob/b6c01763565650b9566034a544455ce9b49a43e3/Modules/Quest/QuestEventHandler.lua#L87
^ <https://github.com/Questie/Questie/pull/3111#issuecomment-893783599> Has example where `USER_QUEST_LOG_CHANGED` fires before related `QUEST_ACCEPTED`. And iirc it fires always before, never after.

https://github.com/Questie/Questie/blob/b6c01763565650b9566034a544455ce9b49a43e3/Modules/Quest/QuestEventHandler.lua#L136
^ `USER_QUEST_LOG_CHANGED` usually fires after `QUEST_TURNED_IN` then this is ok, **but** there is that rare timing when it fires before.

https://github.com/Questie/Questie/blob/b6c01763565650b9566034a544455ce9b49a43e3/Modules/Quest/QuestEventHandler.lua#L160
^ `USER_QUEST_LOG_CHANGED` fires (always) before related `QUEST_REMOVED`

2021-08-11 05:14 UTC, BreakBB commented
Hmmm if `QUEST_ACCEPTED` fires before `USER_QUEST_LOG_CHANGED` then the `sekipNextUQLCEvent`could indeed be a problem 🤔 As we already know we only need the `USER_QUEST_LOG_CHANGED` event for edge cases, when we have to do full scan.

Maybe we are able to use the `questLog.state` for this.

2021-08-16 17:23 UTC, Laumesis commented
Cache was cleared before login. Questie and other addons which would use quest api stuff are disabled, or atleast I think so
```
[19:42:53] VARIABLES_LOADED QuestLog: 432502.636
[19:42:53] PLAYER_LOGIN QuestLog: 432502.948
[19:42:53] PLAYER_ENTERING_WORLD QuestLog: 432502.948
[19:42:53] QUEST_LOG_UPDATE QuestLog: 432502.948
[19:42:53] QUEST_WATCH_LIST_CHANGED QuestLog: 432502.948
[19:42:53] QUEST_LOG_UPDATE QuestLog: 432503.46
[19:42:53] Quest 8712 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:53]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [5]: { type = reputation, numRequired = 1, text = Cenarion Circle:  Revered / Exalted, finished = false, numFulfilled = 0, }
[19:42:53] Quest 8657 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:53]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [5]: { type = reputation, numRequired = 1, text = Brood of Nozdormu:  Honored / Friendly, finished = true, numFulfilled = 1, }
[19:42:53] Quest 8626 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:53]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [5]: { type = reputation, numRequired = 1, text = Brood of Nozdormu:  Honored / Neutral, finished = true, numFulfilled = 1, }
[19:42:53] Quest 8659 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:53]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [5]: { type = reputation, numRequired = 1, text = Brood of Nozdormu:  Honored / Neutral, finished = true, numFulfilled = 1, }
[19:42:53] Quest 9738 : Objectives:
[19:42:53]     [1]: { type = monster, numRequired = 1, text = Earthbinder Rayge Discovered: 1/1, finished = true, numFulfilled = 1, }
[19:42:53]     [2]: { type = monster, numRequired = 1, text = Naturalist Bite Discovered: 1/1, finished = true, numFulfilled = 1, }
[19:42:53]     [3]: { type = monster, numRequired = 1, text = Weeder Greenthumb Discovered: 1/1, finished = true, numFulfilled = 1, }
[19:42:53]     [4]: { type = monster, numRequired = 1, text = Windcaller Claw Discovered: 1/1, finished = true, numFulfilled = 1, }
[19:42:53] Quest 9033 : Objectives:
[19:42:53]     [1]: { type = monster, numRequired = 8, text =   slain: 0/8, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = monster, numRequired = 3, text =   slain: 0/3, finished = false, numFulfilled = 0, }
[19:42:53]     [3]: { type = monster, numRequired = 5, text =   slain: 5/5, finished = true, numFulfilled = 5, }
[19:42:53]     [4]: { type = monster, numRequired = 5, text =   slain: 0/5, finished = false, numFulfilled = 0, }
[19:42:53] Quest 10231 : Objectives:
[19:42:53]     [1]: { type = event, numRequired = 1, text = Beat Down "Dirty" Larry and Get Information, finished = false, numFulfilled = 0, }
[19:42:53] Quest 9248 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = reputation, numRequired = 1, text = Cenarion Circle:  Revered / Honored, finished = true, numFulfilled = 1, }
[19:42:53] Quest 8332 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = item, numRequired = 3, text =  : 0/3, finished = false, numFulfilled = 0, }
[19:42:53] Quest 9419 : Objectives:
[19:42:53]     [1]: { type = monster, numRequired = 1, text = Return Silithyst: 0/1, finished = false, numFulfilled = 0, }
[19:42:53] Quest 8620 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53] Quest 5253 : Objectives:
[19:42:53] Quest 9896 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:53] Quest 9801 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 4, text =  : 3/4, finished = false, numFulfilled = 3, }
[19:42:53]     [2]: { type = item, numRequired = 4, text =  : 3/4, finished = false, numFulfilled = 3, }
[19:42:53] Quest 9780 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 8, text =  : 0/8, finished = false, numFulfilled = 0, }
[19:42:53] Quest 10355 : Objectives:
[19:42:53]     [1]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53]     [2]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:53] Quest 11972 : Objectives:
[19:42:55] QUEST_LOG_UPDATE QuestLog: 432504.847
[19:42:55] Quest 8712 : Objectives:
[19:42:55]     [1]: { type = item, numRequired = 1, text = Qiraji Spiked Hilt: 0/1, finished = false, numFulfilled = 0, }
[19:42:55]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:55]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [5]: { type = reputation, numRequired = 1, text = Cenarion Circle:  Revered / Exalted, finished = false, numFulfilled = 0, }
[19:42:55] Quest 8657 : Objectives:
[19:42:55]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:55]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:55]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [5]: { type = reputation, numRequired = 1, text = Brood of Nozdormu:  Honored / Friendly, finished = true, numFulfilled = 1, }
[19:42:55] Quest 8626 : Objectives:
[19:42:55]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:55]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:55]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [4]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [5]: { type = reputation, numRequired = 1, text = Brood of Nozdormu:  Honored / Neutral, finished = true, numFulfilled = 1, }
[19:42:55] Quest 8659 : Objectives:
[19:42:55]     [1]: { type = item, numRequired = 1, text =  : 0/1, finished = false, numFulfilled = 0, }
[19:42:55]     [2]: { type = item, numRequired = 2, text =  : 0/2, finished = false, numFulfilled = 0, }
[19:42:55]     [3]: { type = item, numRequired = 5, text =  : 0/5, finished = false, numFulfilled = 0, }
[19:42:55]     [4]: { type = item, numRequired = 5, text =   [...]

2021-08-18 10:16 UTC, Laumesis commented
Example of typical quest accept. It depends on many factors how many `QUEST_LOG_UPDATE`s it takes. Can be 1, can be more than 2.
```
UNIT_QUEST_LOG_CHANGED QuestLog: 580937.139
<empty log>

QUEST_ACCEPTED QuestLog: 580937.139
Quest 10116; Wanted: Chieftain Mummaki; 64; Group; false; false; nil; 1; 10116; false; false; false; false; false; false; false; false; false;  Objectives:

QUEST_LOG_UPDATE QuestLog: 580937.139
Quest 10116; Wanted: Chieftain Mummaki; 64; Group; false; false; nil; 1; 10116; false; false; false; false; false; false; false; false; false;  Objectives:

QUEST_LOG_UPDATE QuestLog: 580937.175
Quest 10116; Wanted: Chieftain Mummaki; 64; Group; false; false; nil; 1; 10116; false; false; false; false; false; false; false; false; false;  Objectives:
    [1]: { type = item, numRequired = 1, text = Chieftain Mummaki's Totem: 0/1, finished = false, numFulfilled = 0, }
```

2021-08-18 13:27 UTC, Laumesis commented
Debug code, independet from Questie. Prints quest log when events fire.
```lua
do
local questLog = { ["numQuests"] = 0 }
local tpack = table.pack or function(...) return { n = select("#", ...), ... } end
local tunpack = table.unpack or unpack

--- Can't handle functions
--- Can't handle tables as keys
local function CloneTable(t)
    local ret = {}
    for k,v in pairs(t) do
        if type(v) == "table" then
            ret[k] = CloneTable(v)
        else
            ret[k] = v
        end
    end
    return ret
end

--- Can't handle functions
--- Can't handle tables as keys
--- Can't handle tables as values
local function isEqualTable(a, b)
--	if (not a) or (not b) then
--		return false
--	end
    for k, v in pairs(a) do
        local v2 = b[k]
        if (v2 == nil) or (v ~= v2) then
            return false
        end
    end
    for k, v in pairs(b) do
        local v2 = a[k]
        if (v2 == nil) or (v ~= v2) then
            return false
        end
    end
    return true
end

local function CompareQuestLog()
    local equal = true 
    local _, numQuests = GetNumQuestLogEntries()
    local newQuestLog = { ["numQuests"] = numQuests }
    equal = equal and (numQuests == questLog.numQuests)
    for questLogIndex = 1, 100 do
        local logTitle = tpack(GetQuestLogTitle(questLogIndex))
        local title, isHeader, questId = logTitle[1], logTitle[4], logTitle[8]
        if (not title) then
            break
        end
        if (not isHeader) then
            local quest = questLog[questId]
            equal = equal and (quest and true or false) and isEqualTable(logTitle, quest.logTitle)
            newQuestLog[questId] = { ["logTitle"] = CloneTable(logTitle) }

            local objectiveList = CloneTable(C_QuestLog.GetQuestObjectives(questId))
            newQuestLog[questId].objectiveList = objectiveList
            if equal then
                for k,v in pairs(objectiveList) do
                    local v2 = quest.objectiveList[k]
                    equal = isEqualTable(v, v2)
                    if not equal then break end
                end
            end
        end
    end
    questLog = newQuestLog
    return equal
end

local function ShowIfTrue(var, name)
    return (var and (name.."="..tostring(var).." ") or "")
end

function LauPrintQuestLog(...)
    local _, numQuests = GetNumQuestLogEntries()
    print(..., GetTime(), "QuestLog:", numQuests, "quests:")
    if CompareQuestLog() then
        print("<no changes>")
        return
    end
    for questLogIndex = 1, 100 do
        local title, level, suggestedGroup, isHeader, isCollapsed, isComplete, frequency, questId, startEvent, displayQuestID, isOnMap, hasLocalPOI, isTask, isBounty, isStory, isHidden, isScaling = GetQuestLogTitle(questLogIndex)
        if (not title) then
            -- We exceeded the valid quest log entries
            break
        end
        if (not isHeader) then
            print("Quest "..tostring(questId)
                ..((title and type(title)=="string") and (" '''"..title.."''' ") or (" "..tostring(title).." "))
                .."lvl "..tostring(level).." "
                .."complete="..tostring(isComplete).." "
                ..ShowIfTrue(suggestedGroup, "group")
                ..ShowIfTrue(isHeader, "isHeader")
                ..ShowIfTrue(isCollapsed, "isCollapsed")
                ..((frequency and frequency ~= 1) and ShowIfTrue(frequency, "frequency") or "")
                ..ShowIfTrue(startEvent, "startEvent")
                ..ShowIfTrue(displayQuestID, "displayQuestID")
                ..ShowIfTrue(isOnMap, "isOnMap")
                ..ShowIfTrue(hasLocalPOI, "hasLocalPOI")
                ..ShowIfTrue(isTask, "isTask")
                ..ShowIfTrue(isBounty, "isBounty")
                ..ShowIfTrue(isStory, "isStory")
                ..ShowIfTrue(isHidden, "isHidden")
                ..ShowIfTrue(isScaling, "isSCaling")
                .."Objectives:"
                )
            local objectiveList = C_QuestLog.GetQuestObjectives(questId)
            if objectiveList then
                if #objectiveList == 0 then
                    print("    empty table")
                end
                for i, objective in pairs(objectiveList) do
                    print("    ["..tostring(i).."]: "..tostring(objective.type)
                        .." '''"..tostring(objective.text).."'''  "
                        ..tostring(objective.numFulfilled).."/"..tostring(objective.numRequired)
                        .." = "..tostring(objective.finished).." "
                        )
                end
            elseif objectiveList == nil then
                print("    !!! objectiveList is nil")
            else
                print("    !!!!! objectiveList is false")
            end
        end
    end
end

do
    local printEventFrame = CreateFrame("Frame")
    local function EventHandler(_, event, ...)
        LauPrintQuestLog(event, ...)
    end

--    printEventFrame:RegisterEvent("PLAYER_LOGIN")
--    printEventFrame:RegisterEvent("PLAYER_ENTERING_WORLD")
    printEventFrame:RegisterEvent("UNIT_QUEST_LOG_CHANGED")
    printEventFrame:RegisterEvent("QUEST_LOG_UPDATE")
    printEventFrame:RegisterEvent("QUEST_ACCEPTED")
    printEventFrame:RegisterEvent("QUEST_TURNED_IN")
    printEventFrame:RegisterEvent("QUEST_REMOVED")
    printEventFrame:RegisterEvent("QUEST_ITEM_UPDATE")
--    printEventFrame:RegisterEvent("QUEST_WATCH_LIST_CHANGED")
--    printEventFrame:RegisterEvent("QUEST_WATCH_UPDATE")
--    printEventFrame:RegisterEvent("VARIABLES_LOADED")
--    printEventFrame:RegisterEvent("QUEST_DETAIL")
    printEventFrame:SetScript("OnEvent", EventHandler)
end
end
```

2021-08-18 13:54 UTC, Laumesis commented
Quest log can change already at `UNIT_QUEST_LOG_CHANGED`. objectivesList from API might have incorrect status of subObjectives once quest is complete.
NOTE: This log is from Classic Era - not BCC unlike earlier ones. Log has other quests than 2801 removed from lists.
```
[16:43:24] UNIT_QUEST_LOG_CHANGED 594535.027 Log has 5 quests. Event args: player
[16:43:24] <no changes>
[16:43:24] Quest accepted: A Tale of Sorrow
[16:43:24] QUEST_ACCEPTED 594535.027 Log has 6 quests. Event args: 6 2801
[16:43:24] Quest 2801 '''A Tale of Sorrow''' lvl 57 complete=nil startEvent=true Objectives:
[16:43:24]     [1]: event '''A Tale of Sorrow'''  0/1 = false 
[16:43:24] QUEST_LOG_UPDATE 594535.027 Log has 6 quests. Event args:
[16:43:24] <no changes>
[16:43:25] QUEST_LOG_UPDATE 594536.037 Log has 6 quests. Event args:
[16:43:25] <no changes>

[16:43:48] UNIT_QUEST_LOG_CHANGED 594558.913 Log has 6 quests. Event args: player
[16:43:48] Quest 2801 '''A Tale of Sorrow''' lvl 57 complete=1 startEvent=true Objectives:
[16:43:48]     [1]: event '''A Tale of Sorrow'''  0/1 = false 
[16:43:48] QUEST_LOG_UPDATE 594558.913 Log has 6 quests. Event args:
[16:43:48] <no changes>
[16:43:49] QUEST_LOG_UPDATE 594559.921 Log has 6 quests. Event args:
[16:43:49] <no changes>
[16:44:47] Dump: value=C_QuestLog.GetQuestObjectives(2801)
[16:44:47] [1]={
[16:44:47]   [1]={
[16:44:47]     type="event",
[16:44:47]     numRequired=1,
[16:44:47]     text="A Tale of Sorrow",
[16:44:47]     finished=false,
[16:44:47]     numFulfilled=0
[16:44:47]   }
[16:44:47] }

[16:45:44] A Tale of Sorrow completed.
[16:45:44] Received 36 Silver.
[16:45:44] QUEST_TURNED_IN 594675.854 Log has 6 quests. Event args: 2801 0 3600
[16:45:44] <no changes>
[16:45:45] UNIT_QUEST_LOG_CHANGED 594676.275 Log has 6 quests. Event args: player
[16:45:45] Quest 2801 '''A Tale of Sorrow''' lvl 57 complete=nil startEvent=true Objectives:
[16:45:45]     [1]: event '''A Tale of Sorrow'''  0/1 = false 
[16:45:45] QUEST_REMOVED 594676.275 Log has 5 quests. Event args: 2801
(just other quests)
[16:45:45] QUEST_LOG_UPDATE 594676.275 Log has 5 quests. Event args:
[16:45:45] <no changes>
```

2021-08-18 14:33 UTC, Laumesis commented
Log from Classic Era for completing quest 2681 and then turn in of it. Other quests removed from log.
```
[17:24:38] UNIT_QUEST_LOG_CHANGED 597008.926 Log has 6 quests. Event args: player
[17:24:38] Quest 2681 '''The Stones That Bind Us''' lvl 57 complete=nil Objectives:
[17:24:38]     [1]: monster '''Servants of Razelikh Freed: 8/9'''  8/9 = false 
[17:24:38]     [2]: monster '''Servants of Grol Freed: 3/3'''  3/3 = true 
[17:24:38]     [3]: monster '''Servants of Allistarj Freed: 3/3'''  3/3 = true 
[17:24:38]     [4]: monster '''Servants of Sevine Freed: 3/3'''  3/3 = true 
[17:24:38] QUEST_LOG_UPDATE 597008.926 Log has 6 quests. Event args:
[17:24:38] <no changes>
[17:24:39] QUEST_LOG_UPDATE 597009.938 Log has 6 quests. Event args:
[17:24:39] <no changes>

[17:25:22] UNIT_QUEST_LOG_CHANGED 597053.42 Log has 6 quests. Event args: player
[17:25:22] Quest 2681 '''The Stones That Bind Us''' lvl 57 complete=1 Objectives:
[17:25:22]     [1]: monster '''Servants of Razelikh Freed: 9/9'''  9/9 = true 
[17:25:22]     [2]: monster '''Servants of Grol Freed: 3/3'''  3/3 = true 
[17:25:22]     [3]: monster '''Servants of Allistarj Freed: 3/3'''  3/3 = true 
[17:25:22]     [4]: monster '''Servants of Sevine Freed: 3/3'''  3/3 = true 
[17:25:22] QUEST_LOG_UPDATE 597053.42 Log has 6 quests. Event args:
[17:25:22] <no changes>
[17:25:23] QUEST_LOG_UPDATE 597054.431 Log has 6 quests. Event args:
[17:25:23] <no changes>

[17:28:08] UNIT_QUEST_LOG_CHANGED 597219.105 Log has 6 quests. Event args: player
[17:28:08] Quest 2681 '''The Stones That Bind Us''' lvl 57 complete=nil Objectives:
[17:28:08]     [1]: monster '''Servants of Razelikh Freed: 0/9'''  0/9 = false 
[17:28:08]     [2]: monster '''Servants of Grol Freed: 0/3'''  0/3 = false 
[17:28:08]     [3]: monster '''Servants of Allistarj Freed: 0/3'''  0/3 = false 
[17:28:08]     [4]: monster '''Servants of Sevine Freed: 0/3'''  0/3 = false 
[17:28:08] QUEST_REMOVED 597219.105 Log has 5 quests. Event args: 2681
[17:28:08] QUEST_LOG_UPDATE 597219.105 Log has 5 quests. Event args:
[17:28:08] <no changes>
[17:28:08] The Stones That Bind Us completed.
[17:28:08] Received 4 Gold, 53 Silver.
[17:28:08] QUEST_TURNED_IN 597219.126 Log has 5 quests. Event args: 2681 0 45300
[17:28:08] <no changes>
```

2021-08-23 05:18 UTC, Laumesis commented
Now I remember why I did `BANKFRAME_CLOSED` event differently in one addon.
You can't handle every 2nd one blindly. If you walk away from bank, it fires only single event. Either look for opening event or handle only 1 event per frame with GetTime().

2021-11-13 01:53 UTC, Laumesis commented
Some logs from completing <https://tbc.wowhead.com/quest=1385/brutal-politics> , which has solely reputation objective.
```
[03:41:16] Questie: [DEVELOP] [QuestieTooltips:GetTooltip] m_4649
[03:41:17] Questie: [SPAM] [QuestieNameplate:DrawTargetFrame]
[03:41:22] Questie: [DEVELOP] [EVENT] PLAYER_REGEN_DISABLED
[03:41:23] Questie: [SPAM] [QuestieNameplate:DrawTargetFrame]
[03:41:23] Reputation with Magram Clan Centaur increased by 20.
[03:41:23] Questie: [DEVELOP] CHAT_MSG_COMBAT_FACTION_CHANGE
[03:41:23] Questie: [DEVELOP] QuestieReputation: Update
[03:41:23] Questie: [DEVELOP] QuestieReputation: Update - faction "Magram Clan Centaur" (93) changed
[03:41:23] Questie: [INFO] [QuestieQuest] 0 available quests drawn. PlayerLevel = 61
[03:41:23] You are now Friendly with Magram Clan Centaur.
[03:41:23] Reputation with Gelkis Clan Centaur decreased by 100.
[03:41:23] Questie: [DEVELOP] CHAT_MSG_COMBAT_FACTION_CHANGE
[03:41:23] Questie: [DEVELOP] QuestieReputation: Update
[03:41:23] QUEST_LOG_UPDATE 171969.417 Log has 9 quests. Event args:
[03:41:23] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[03:41:23]     [1]:  item '''Eye of the Emberseer: 0/1'''  0/1 = false 
[03:41:23] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[03:41:23]     [1]:  item '''Doomrigger's Clasp: 0/1'''  0/1 = false 
[03:41:23] Quest 1385 '''Brutal Politics''' lvl 35 complete=1 Objectives:
[03:41:23]     [1]:  reputation '''Magram Clan Centaur:  Friendly / Friendly'''  1/1 = true 
[03:41:23] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[03:41:23]     [1]:  monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[03:41:23]     [2]:  monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[03:41:23]     [3]:  monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[03:41:23]     [4]:  monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[03:41:23] Quest 9211 '''The Ice Guard''' lvl 60 complete=nil Objectives:
[03:41:23]     [1]:  item '''Insignia of the Crusade: 0/10'''  0/10 = false 
[03:41:23] Quest 9213 '''The Shadow Guard''' lvl 60 complete=nil Objectives:
[03:41:23]     [1]:  item '''Insignia of the Crusade: 0/10'''  0/10 = false 
[03:41:23] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[03:41:23]     [1]:  item '''Argent Dawn Valor Token: 0/1'''  0/1 = false 
[03:41:23] Quest 10161 '''In Case of Emergency...''' lvl 61 complete=nil Objectives:
[03:41:23]     [1]:  item '''Zeppelin Debris: 0/30'''  0/30 = false 
[03:41:23] Quest 9349 '''Ravager Egg Roundup''' lvl 61 complete=nil Objectives:
[03:41:23]     [1]:  item '''Ravager Egg: 0/12'''  0/12 = false 
[03:41:23] [Quest Event] QUEST_LOG_UPDATE
[03:41:25] Questie: [DEVELOP] [EVENT] PLAYER_REGEN_ENABLED
[03:41:25] Questie: [DEVELOP] QuestieTracker: ResetLinesForChange
[03:41:25] Questie: [DEVELOP] QuestieTracker: Update
```

Unfiltered /etrace. Only 1 event if searching for `quest`. :
![image](https://user-images.githubusercontent.com/75958501/141601430-d32d07ef-15a8-4217-806b-e33779a5f090.png)
![image](https://user-images.githubusercontent.com/75958501/141601438-654c900b-02ef-434b-a44c-732df0ebcae3.png)

2021-11-13 01:57 UTC, Laumesis commented
At previous message quest complete change Questie Tracker updated correctly, but turn in location did not get spawned on maps

2021-11-13 02:04 UTC, Laumesis commented
Relog and still on same quest. I killed one opposite faction mob, resulting the quest no more complete. Questie Tracker updated correctly. Map has still turn in npc marked. Should have vanished...
```

[03:55:53] PLAYER_LOGIN 172838.769 Log has 9 quests. Event args:
[03:55:53] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[03:55:53]     [1]:  item '''Eye of the Emberseer: 0/1'''  0/1 = false 
[03:55:53] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[03:55:53]     [1]:  item '''Doomrigger's Clasp: 0/1'''  0/1 = false 
[03:55:53] Quest 1385 '''Brutal Politics''' lvl 35 complete=1 Objectives:
[03:55:53]     [1]:  reputation '''Magram Clan Centaur:  Friendly / Friendly'''  1/1 = true 
[03:55:53] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[03:55:53]     [1]:  monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[03:55:53]     [2]:  monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[03:55:53]     [3]:  monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[03:55:53]     [4]:  monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[03:55:53] Quest 9211 '''The Ice Guard''' lvl 60 complete=nil Objectives:
[03:55:53]     [1]:  item '''Insignia of the Crusade: 0/10'''  0/10 = false 
[03:55:53] Quest 9213 '''The Shadow Guard''' lvl 60 complete=nil Objectives:
[03:55:53]     [1]:  item '''Insignia of the Crusade: 0/10'''  0/10 = false 
[03:55:53] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[03:55:53]     [1]:  item '''Argent Dawn Valor Token: 0/1'''  0/1 = false 
[03:55:53] Quest 10161 '''In Case of Emergency...''' lvl 61 complete=nil Objectives:
[03:55:53]     [1]:  item '''Zeppelin Debris: 0/30'''  0/30 = false 
[03:55:53] Quest 9349 '''Ravager Egg Roundup''' lvl 61 complete=nil Objectives:
[03:55:53]     [1]:  item '''Ravager Egg: 0/12'''  0/12 = false 

[03:58:55] Questie: [DEVELOP] [QuestieTooltips:GetTooltip] m_4640
[03:58:55] Questie: [SPAM] [QuestieNameplate:DrawTargetFrame]
[03:59:00] Questie: [DEVELOP] [EVENT] PLAYER_REGEN_DISABLED
[03:59:03] Questie: [SPAM] [QuestieNameplate:NameplateCreated]
[03:59:08] Questie: [SPAM] [QuestieNameplate:DrawTargetFrame]
[03:59:08] Reputation with Gelkis Clan Centaur increased by 20.
[03:59:08] Questie: [DEVELOP] CHAT_MSG_COMBAT_FACTION_CHANGE
[03:59:08] Questie: [DEVELOP] QuestieReputation: Update
[03:59:08] Reputation with Magram Clan Centaur decreased by 100.
[03:59:08] Questie: [DEVELOP] CHAT_MSG_COMBAT_FACTION_CHANGE
[03:59:08] Questie: [DEVELOP] QuestieReputation: Update
[03:59:08] Questie: [DEVELOP] QuestieReputation: Update - faction "Magram Clan Centaur" (93) changed
[03:59:08] Questie: [INFO] [QuestieQuest] 0 available quests drawn. PlayerLevel = 61
[03:59:08] You are now Neutral with Magram Clan Centaur.
[03:59:08] QUEST_LOG_UPDATE 173034.518 Log has 9 quests. Event args:
[03:59:08] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[03:59:08]     [1]:  item '''Eye of the Emberseer: 0/1'''  0/1 = false 
[03:59:08] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[03:59:08]     [1]:  item '''Doomrigger's Clasp: 0/1'''  0/1 = false 
[03:59:08] Quest 1385 '''Brutal Politics''' lvl 35 complete=nil Objectives:
[03:59:08]     [1]:  reputation '''Magram Clan Centaur:  Neutral / Friendly'''  0/1 = false 
[03:59:08] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[03:59:08]     [1]:  monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[03:59:08]     [2]:  monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[03:59:08]     [3]:  monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[03:59:08]     [4]:  monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[03:59:08] Quest 9211 '''The Ice Guard''' lvl 60 complete=nil Objectives:
[03:59:08]     [1]:  item '''Insignia of the Crusade: 0/10'''  0/10 = false 
[03:59:08] Quest 9213 '''The Shadow Guard''' lvl 60 complete=nil Objectives:
[03:59:08]     [1]:  item '''Insignia of the Crusade: 0/10'''  0/10 = false 
[03:59:08] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[03:59:08]     [1]:  item '''Argent Dawn Valor Token: 0/1'''  0/1 = false 
[03:59:08] Quest 10161 '''In Case of Emergency...''' lvl 61 complete=nil Objectives:
[03:59:08]     [1]:  item '''Zeppelin Debris: 0/30'''  0/30 = false 
[03:59:08] Quest 9349 '''Ravager Egg Roundup''' lvl 61 complete=nil Objectives:
[03:59:08]     [1]:  item '''Ravager Egg: 0/12'''  0/12 = false 
[03:59:08] [Quest Event] QUEST_LOG_UPDATE
[03:59:09] Questie: [DEVELOP] [EVENT] PLAYER_REGEN_ENABLED
[03:59:09] Questie: [DEVELOP] QuestieTracker: ResetLinesForChange
[03:59:09] Questie: [DEVELOP] QuestieTracker: Update
[04:00:20] Questie: [DEVELOP] [QuestieTooltips:GetTooltip] m_4640
```
![image](https://user-images.githubusercontent.com/75958501/141601796-e77cfc0c-8327-4df2-89c8-f4875de21d86.png)

2021-11-13 02:46 UTC, Laumesis commented
Imo QuestEventHandler's init should be changed so that most of events are registered only after we have initialised `state = QUEST_LOG_STATES.QUEST_ACCEPTED` and done `QuestieHash:InitQuestLogHashes()`.

2021-11-13 03:39 UTC, Laumesis commented
Not directly related to this PR (I hope), but turn in icons from maps are not removed when realted quest progresses backwards

2022-01-06 20:29 UTC, Laumesis requested changes

2022-01-07 07:40 UTC, BreakBB commented on Modules/Libs/QuestieLib.lua
> +---@return number, number questLevel & requiredLevel
Nope 🙈 The plugin does not highlight the second <type>

2022-01-07 07:43 UTC, BreakBB commented on Modules/Libs/QuestieHash.lua
> +        questObjectives = QuestieLib:GetQuestObjectives(questId),
I must have missed that. Replaced this line as well and removed the lib function

2022-01-07 07:47 UTC, BreakBB commented on Database/QuestieDB.lua
> +    QO.ObjectiveData = {}
I don't fully understand what should be added and where. You could use the "Insert a suggestion" of GitHub to propose your changes.

2022-01-07 07:52 UTC, BreakBB commented on Modules/Quest/QuestieQuest.lua
> +                    QuestieAnnounce:AnnounceParty(questId, "objective", nil, text, tostring(objective.numFulfilled) .. "/" .. tostring(objective.numRequired))
I added a TODO to `QuestieAnnounce:AnnounceParty`

> Split this function into "AnnounceObjectiveToParty" and "AnnounceQuestItemLootedToParty" (or something similar)

No need to keep both in the same function. Epecially that `itemId` is not used in both cases shows that this is bad code (buh!).

2022-01-07 11:41 UTC, Laumesis commented on Modules/Libs/QuestieLib.lua
> +---@return number, number questLevel & requiredLevel
Well, then we should use
`---@return number, number @questLevel & requiredLevel`
or
`---@return number, number -- questLevel & requiredLevel`

As VSCode lua extension interprets current code having `questLevel` as 2nd return value even it is 1st one in real.

2022-01-07 11:51 UTC, Laumesis commented on Database/QuestieDB.lua
> +    QO.ObjectiveData = {}
In this case I can't use it as change is to lines not yet changed within this PR.

And I ment including this change into PR:
https://github.com/Questie/Questie/pull/3248/files#diff-ff09bbcb7092e4779ce63b87f62d766883085a5461fc8be499725451cb4eb37dR640

2022-01-13 02:40 UTC, Laumesis commented
Few samples of game cache's questlog filling at login/reload:

**Character has quests. Cache deleted. Login:**
```raw
[03:59:43] ArkInventory: Loading Connected Realm (EU) Data
[03:59:43] ADDON_LOADED 756979.89 Log has 0 quests. nil Event args: LauInit
[03:59:43] <no changes>
[03:59:43] ADDON_LOADED 756979.89 Log has 0 quests. nil Event args: WideQuestLog
[03:59:43] <no changes>
[03:59:43] ADDON_LOADED 756979.89 Log has 0 quests. nil Event args: WideQuestLogLevels
[03:59:43] <no changes>
[03:59:43] ADDON_LOADED 756979.89 Log has 0 quests. nil Event args: zz_Coords
[03:59:43] <no changes>
[03:59:43] VARIABLES_LOADED 756984.773 Log has 0 quests. nil Event args:
[03:59:43] <no changes>
[03:59:43] Guild Message of the Day: ***************
[03:59:43] ADDON_LOADED 756984.909 Log has 0 quests. nil Event args: Blizzard_CombatLog
[03:59:43] <no changes>
[03:59:43] ArkInventory: v3.09.63 [Classic] Enabled
[03:59:43] ArkInventory: Rules Enabled
[03:59:43] PLAYER_LOGIN 756984.909 Log has 0 quests. nil Event args:
[03:59:43] <no changes>
[03:59:43] ADDON_LOADED 756984.909 Log has 0 quests. nil Event args: Blizzard_CombatText
[03:59:43] <no changes>
[03:59:43] PLAYER_ENTERING_WORLD 756984.909 Log has 0 quests. nil Event args: true false
[03:59:43] <no changes>
[03:59:43] LOADING_SCREEN_DISABLED 756984.909 Log has 0 quests. nil Event args:
[03:59:43] <no changes>
[03:59:43] QUEST_LOG_UPDATE 756984.909 Log has 0 quests. nil Event args:
[03:59:43] <no changes>
[03:59:43] QUEST_WATCH_LIST_CHANGED 756984.909 Log has 0 quests. nil Event args: nil nil
[03:59:43] <no changes>
[03:59:43] SPELLS_CHANGED 756984.909 Log has 0 quests. nil Event args:
[03:59:43] <no changes>
[03:59:43] ArkInventory: Rules: ItemRack Enabled
[03:59:43] QUEST_LOG_UPDATE 756985.236 Log has 5 quests. nil Event args:
[03:59:43] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[03:59:43]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:43] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[03:59:43]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:43] Quest 7703 '''Unfinished Gordok Business''' lvl 60 complete=nil group=Dungeon Objectives:
[03:59:43]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:43] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[03:59:43]     [1]: monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[03:59:43]     [2]: monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[03:59:43]     [3]: monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[03:59:43]     [4]: monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[03:59:43] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[03:59:43]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:44] QUEST_LOG_UPDATE 756985.549 Log has 5 quests. nil Event args:
[03:59:44] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[03:59:44]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:44] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[03:59:44]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:44] Quest 7703 '''Unfinished Gordok Business''' lvl 60 complete=nil group=Dungeon Objectives:
[03:59:44]     [1]: item ''' : 0/1'''  0/1 = false 
[03:59:44] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[03:59:44]     [1]: monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[03:59:44]     [2]: monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[03:59:44]     [3]: monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[03:59:44]     [4]: monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[03:59:44] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[03:59:44]     [1]: item '''Argent Dawn Valor Token: 0/1'''  0/1 = false 
[03:59:44] SPELLS_CHANGED 756985.549 Log has 5 quests. nil Event args:
[03:59:44] <no changes>
[03:59:44] QUEST_LOG_UPDATE 756985.584 Log has 5 quests. nil Event args:
[03:59:44] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[03:59:44]     [1]: item '''Eye of the Emberseer: 0/1'''  0/1 = false 
[03:59:44] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[03:59:44]     [1]: item '''Doomrigger's Clasp: 0/1'''  0/1 = false 
[03:59:44] Quest 7703 '''Unfinished Gordok Business''' lvl 60 complete=nil group=Dungeon Objectives:
[03:59:44]     [1]: item '''Gauntlet of Gordok Might: 0/1'''  0/1 = false 
[03:59:44] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[03:59:44]     [1]: monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[03:59:44]     [2]: monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[03:59:44]     [3]: monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[03:59:44]     [4]: monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[03:59:44] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[03:59:44]     [1]: item '''Argent Dawn Valor Token: 0/1'''  0/1 = false 
```

**Character has quests. /reload:**
```raw
[04:00:50] ArkInventory: Loading Connected Realm (EU) Data
[04:00:50] ADDON_LOADED 757047.79 Log has 5 quests. nil Event args: LauInit
[04:00:50] Quest 6821 '''Eye of the Emberseer''' lvl 60 complete=nil group=Raid Objectives:
[04:00:50]     [1]: item '''Eye of the Emberseer: 0/1'''  0/1 = false 
[04:00:50] Quest 4764 '''Doomrigger's Clasp''' lvl 60 complete=nil group=Raid Objectives:
[04:00:50]     [1]: item '''Doomrigger's Clasp: 0/1'''  0/1 = false 
[04:00:50] Quest 7703 '''Unfinished Gordok Business''' lvl 60 complete=nil group=Dungeon Objectives:
[04:00:50]     [1]: item '''Gauntlet of Gordok Might: 0/1'''  0/1 = false 
[04:00:50] Quest 9664 '''Establishing New Outposts''' lvl 60 complete=nil group=PvP Objectives:
[04:00:50]     [1]: monster '''Capture Crown Guard Tower: 0/1'''  0/1 = false 
[04:00:50]     [2]: monster '''Capture Eastwall Tower: 0/1'''  0/1 = false 
[04:00:50]     [3]: monster '''Capture Northpass Tower: 0/1'''  0/1 = false 
[04:00:50]     [4]: monster '''Capture Plaguewood Tower: 0/1'''  0/1 = false 
[04:00:50] Quest 9141 '''They Call Me "The Rooster"''' lvl 60 complete=nil Objectives:
[04:00:50]     [1]: item '''Argent Dawn Valor Token: 0/1'''  0/1 = false 
[04:00:50] ADDON_LOADED 757047.79 Log has 5 quests. nil Event args: WideQuestLog
[04:00:50] <no changes>
[04:00:50] ADDON_LOADED 757047.79 Log has 5 quests. nil Event args: WideQuestLogLevels
[04:00:50] <no changes>
[04:00:50] ADDON_LOADED 757047.79 Log has 5 quests. nil Event args: zz_Coords
[04:00:50] <no changes>
[04:00:50] VARIABLES_LOADED 757047.79 Log has 5 quests. nil Event args:
[04:00:50] <no changes>
[04:00:50] Guild Message of the Day: ******
[04:00:50] ADDON_LOADED 757047.79 Log has 5 quests. nil Event args: Blizzard_CombatLog
[04:00:50] <no changes>
[04:00:50] ArkInventory: v3.09.63 [Classic] Enabled
[04:00:50] ArkInventory: Rules Enabled
[04:00:50] PLAYER_LOGIN 757047.79 Log has 5 quests. nil Event args:
[04:00:50] <no changes>
[04:00:50] ADDON_LOADED 757047.79 Log has 5 quests. nil Event args: Blizzard_CombatText
[04:00:50] <no changes>
[04:00:50] PLAYER_ENTERING_WORLD 757047.79 Log has 5 quests. nil Event args: false true
[04:00:50] <no changes>
[04:00:50] LOADING_SCREEN_DISABLED 757047.79 Log has 5 quests. nil Event args:
[04:00:50] <no changes>
[04:00:50] QUEST_LOG_UPDATE 757051.788 Log has 5 quests. nil Event args:
[04:00:50] <no changes>
[04:00:50] QUEST_WATCH_LIST_CHANGED 757051.788 Log has 5 quests. nil Event args: nil nil
[04:00:50] <no changes>
[04:00:50] SPELLS_CHANGED 757051.788 Log has 5 quests. nil Event args:
[04:00:50] <no changes>
[04:00:50] ArkInventory: Rules: ItemRack Enabled
```

**Character has quests. Cache exists. Login:**
```raw
[04:11:25] ArkInventory: Loading Connected Realm (EU) Data
[04:11:25] ADDON_LOADED 757682.004 Log has 0 quests. nil Event args: LauInit
[04:11:25] <no changes>
[04:11: [...]

2022-01-13 04:54 UTC, Laumesis commented
Note: Required test for future in PTR when blizzard is going to release a new phase - as those usually may have bigger changes to how things work.

1. Delete game cache.  For example the directory: `...\_classic_era_\Cache\`.
2. Login a character having **many** quests in quest log.
3. /reload
4. Logout and login the character again.
5. Login another character having **0** quests in quest log. (Or if you use same character, then delete game cache again after emptying the quest log).
6. /reload
7. Logout and login the character again.

2022-01-22 05:56 UTC, Laumesis commented on Modules/Quest/QuestEventHandler.lua
> +        return
Should also here be `skipNextUQLCEvent = true` as in other return branch? I don't know.

2022-01-22 06:05 UTC, Laumesis commented on Modules/Quest/QuestEventHandler.lua
> +        -- Check for failing recursion. Something is up if the objective texts are still invalid.
Only single counter is used for all quests that are possibly in accept process at the same time and the counter is not zeroed after fail.

Also after more experience with game current behavior, I would maybe just remove whole "failing recursion" check.
Maybe just add some timer for if the objectives aren't good even in 15 seconds print message for user to report the case. Do NOT do anything else in timer than print message.

2022-01-22 06:10 UTC, Laumesis commented on Modules/Quest/QuestEventHandler.lua
> +    if unitTarget ~= "player" then
Maybe filter with unitTarget == "player" before calling the function at all. It is not interest for us if other group members quest log changes.

fyi: There is also now way to register event fire only for certain unit, but I am not sure can it be used for this and the functionality had some "small prints" on usage. So better not use it now.

2022-01-26 03:54 UTC, Laumesis commented
TODO: check if quest items from/to guild bank has to be catched with own event

2022-04-13 15:54 UTC, merged