[feature] Add option to enable coordinates on Mini World Map
Questie/Questie pull request #5621
Opened 2024-02-03 11:06 UTC by viliger2

## Proposed changes

- Add an option to enable map coordinates on Mini World Map's title, similar to how it works currently on full sized World Map. 

## Known issues

- There is a small issue of "Show Mini World Map Coordinates" not fitting existing option structure, so I had to trim it manually to "Mini World Map Coord.".
- Map's original title shows up for a moment when changing zones and when you open a map after closing it with any other zone being selected that is not your current one. This is most likely because Blizzard UI changing title to match currently selected zone before WriteCoords has a chance to be run due to it having relatively low update interval. I don't think this is a major issue, but I understand if pull request will be rejected because of it.

## Screenshots
![image](https://github.com/Questie/Questie/assets/53978306/20904f42-8e72-431b-aecc-b88448d1c1f2)
![image](https://github.com/Questie/Questie/assets/53978306/a06bbbe7-3e88-4454-8a53-95c201a205da)
![image](https://github.com/Questie/Questie/assets/53978306/2c236566-d477-4e92-8e0b-de9f14d86e0c)

2024-02-06 06:38 UTC, BreakBB commented
Hey @viliger2 thanks for bringing this up! I'll look into this shortly to fully review, test and hopefully merge it 😬

2024-02-12 15:08 UTC, BreakBB requested changes
Hey @viliger2 

I added a few really minor points about code style, which you can ignore if you want to.

A big question from my side is: Do we even need a new option? As a user I would honestly not expect to have an option to show the title on the fullscreen map while I can choose to not show it on the small version. I think we are good to have a single option to either show it or not and use it for both, fullscreen and "mini world map".

Maybe you had something differently in mind?

2024-02-12 15:08 UTC, BreakBB commented on Modules/QuestieCoordinates.lua
> +function QuestieCoords:ResetMiniWorldMapText()
```suggestion
function QuestieCoords.ResetMiniWorldMapText()
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/QuestieCoordinates.lua
> +            if(miniWorldMapTitleText) then
```suggestion
            if miniWorldMapTitleText then
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/QuestieCoordinates.lua
> +    if(currentMapId) then
```suggestion
    if currentMapId then
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/QuestieCoordinates.lua
> +        if(info) then
```suggestion
        if info then
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/QuestieCoordinates.lua
> +        if(Questie.db.profile.miniWorldMapCoordinatesEnabled) then
```suggestion
        if Questie.db.profile.miniWorldMapCoordinatesEnabled then
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/QuestieCoordinates.lua
> +        if (regions[i].SetText) then
```suggestion
        if regions[i].SetText then
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/Options/GeneralTab/QuestieOptionsGeneral.lua
> +                            if not value then
```suggestion
                            if (not value) then
```

2024-02-12 15:08 UTC, BreakBB commented on Modules/Options/GeneralTab/QuestieOptionsGeneral.lua
> +                        desc = function() return l10n("Place the Player's coordinates and Cursor's coordinates on the Mini World Map's title."); end,
These two new strings need a corresponding translation entry in https://github.com/Questie/Questie/blob/master/Localization/Translations/Options/General.lua

2024-02-12 15:18 UTC, BreakBB commented
> > Maybe you had something differently in mind?
> 
> Mostly the fact that some people might get uppity if you change current functionality. You know how it is when you change stuff.

Honestly I think the change was when Blizzard introduced the mini world map and Questie didn't add the title to it 🤔 I personally think it's enough to simply always show the title on the mini version, if the option is enabled.

Also: Thanks for the quick reply! 👍🏻

2024-02-12 15:21 UTC, viliger2 commented
I am fine with merging options. I'll update the PR with Russian localisation.

2024-02-13 13:48 UTC, BreakBB commented
Sounds good @viliger2 👍🏻

2024-02-14 16:00 UTC, viliger2 commented
I've removed separate option for mini world map. And since that option no longer exists, we don't need additional localisation.

2024-02-20 07:05 UTC, BreakBB commented
Thank you very much @viliger2 - Tested and verified 👍🏻

2024-02-20 07:05 UTC, BreakBB approved these changes

2024-02-20 07:09 UTC, merged