[quest] Add Warrior's 'Blood Surge' rune
Questie/Questie pull request #5694
Opened 2024-02-16 10:08 UTC by Sommos

## Issue references

Fixes #5693 
Linked To #5636 

## Proposed changes

- ADDED: 'Blood Surge' Warrior fake rune quests

2024-02-16 11:01 UTC, BreakBB requested changes

2024-02-16 11:01 UTC, BreakBB commented on Database/Corrections/sodQuestFixes.lua
> +            [questKeys.startedBy] = {nil,nil,{213422}},
Questie currently does not handle `item`starters. So with this, the rune simply will not show. Please add the NPC starters for now.

2024-02-19 10:00 UTC, Sommos commented on Database/Corrections/sodQuestFixes.lua
> +            [questKeys.startedBy] = {{2255,2569}},
When this was made, it was still unclear what mobs dropped them, so was waiting on a relatively complete list so thank you for catching it!

Fixed in: https://github.com/Questie/Questie/pull/5694/commits/3e65084e47b99bcb93b6c2b508372c8928692392

2024-02-19 15:02 UTC, BreakBB approved these changes

2024-02-19 15:02 UTC, merged